### ISSUE TITLE
Display letters and numbers on Leaflet.IconMaterial icons

### ISSUE THREAD

**Issue by DreamStudioCode** [ilyankou/Leaflet.IconMaterial#2]
Very cool to be able to assign icon background colors! 
We've used for hurricane relief donations:
https://statedata.github.io/community/maps/hubs/#us.ga_to_bs

Can you recommend a way to display numbers on the icons?  1, 2, 3, 4, etc.

**Comment by ilyankou** [comment]
Hey @datascape :

Glad you implemented it in your project! Since the library is designed for Material icons, either use these:
https://material.io/resources/icons/?search=looks_&style=baseline

or look at a `DivIcon` library that lets you use HTML text instead of an icon, so you can put your number as text instead.
https://www.wrld3d.com/wrld.js/latest/docs/leaflet/L.DivIcon/

Hope this helps!
